name: Cite-survie
author: MileKat
main: fr.milekat.cite_survie.MainSurvie
version: '1.0'
api-version: '1.16'
description: plugin cite au émeraudes par MileKat - gestion du survie
depend: [Cite-libs, Cite-core, MysqlPlayerDataBridge]